package com.bodyweight.fitness

object Constants {
    val MAXIMUM_NUMBER_OF_SETS = 12
    val PRIMARY_KEY_ROUTINE_ID = "primaryKeyRoutineId"

    val PREFERENCE_DEFAULT_ROUTINE = "PREFERENCE_DEFAULT_ROUTINE"
    val PREFERENCE_WEIGHT_MEASUREMENT_UNITS = "PREFERENCE_WEIGHT_MEASUREMENT_UNITS"
    val PREFERENCE_PLAY_SOUND_WHEN_TIMER_STOPS = "PREFERENCE_PLAY_SOUND_WHEN_TIMER_STOPS"
    val PREFERENCE_AUTOMATICALLY_LOG_WORKOUT_TIME = "PREFERENCE_AUTOMATICALLY_LOG_WORKOUT_TIME"
    val PREFERENCE_KEEP_SCREEN_ON = "PREFERENCE_KEEP_SCREEN_ON"
    val PREFERENCE_TIMER_KEY = "PREFERENCE_TIMER_KEY_"
    val PREFERENCE_NUMBER_OF_REPS_KEY = "PREFERENCE_NUMBER_OF_REPS_KEY_"
}